version: "2.3"
services:
    milvus_ro:
        restart: always
        image: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
        ports:
            - 19530
        volumes:
            - ./test:/var/lib/milvus/db
            - ./cluster_ro_server.yml:/var/lib/milvus/conf/server_config.yaml
        networks:
            - my-net

networks:
    my-net:
      external: true

