version: "2.3"
services:
    mishards:
        restart: always
        image: milvusdb/mishards
        ports:
            - "0.0.0.0:19540:19530"
        volumes:
            - ./test_mi:/tmp/milvus/db
            # - /tmp/mishards_env:/source/mishards/.env
        command: ["python", "mishards/main.py"]
        environment:
            FROM_EXAMPLE: 'true'
            SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:milvusroot@10.0.0.2:3306/milvus
            DEBUG: 'true'
            SERVER_PORT: 19530
            WOSERVER: tcp://10.0.0.3:19530
            DISCOVERY_PLUGIN_PATH: static
            DISCOVERY_STATIC_HOSTS: 10.0.0.3, 10.0.0.4, 10.0.0.5, 10.0.0.6
            DISCOVERY_STATIC_PORT: 19530
        networks:
            - "my-net"
networks:
    my-net:
        external: true



